---
- name: "install Erlang when version is defined"
  apt:
    name: "erlang{{erlang_suffix }}={{ erlang_version }}"
    update_cache: yes
    force: yes
  when:
    - erlang_version is defined
  tags:
    - erlang
    - erlang-install-version

- name: install Erlang at latest
  apt:
    name: "erlang{{ erlang_suffix }}"
    update_cache: yes
    state: latest
  when:
     - erlang_version is undefined
  tags:
    - erlang
    - erlang-install-latest

